### ISSUE TITLE
how to fix "hGetContents: invalid argument (invalid byte sequence)" and "thread blocked indefinitely in an MVar operation"?

### ISSUE THREAD

**Issue by luckypoem** [walkie/WebPage#1]
hi.

root@AR:/usr/local/walkie-WebPage# .stack-work/dist/i386-linux/Cabal-1.22.5.0/build/hakyll/hakyll build
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  updated blurbs/activities.md
  updated blurbs/links.md
  updated blurbs/optional-announce.md
  updated blurbs/research-overview.md
  updated blurbs/students.md
  updated blurbs/teaching-current.md
  updated css/all.less
hakyll: fd:5: hGetContents: invalid argument (invalid byte sequence)
hakyll: thread blocked indefinitely in an MVar operation
root@AR:/usr/local/walkie-WebPage#

**Comment by walkie** [comment]
Based on [this issue](https://github.com/curry-club-aux/curry-club-augsburg.de/issues/63), it looks like you resolved this problem?

**Comment by luckypoem** [comment]
yes,tks
